### ISSUE TITLE
index.html - Line 25

### ISSUE THREAD

**Issue by Default4152** [KellyDesigns/prj-rev-bwfs-tea-cozy#2]
Important for errors - Line 25 of `index.html` has a class property which appears to be attempting to set it equal to `mission-background`. This initialization is missing an `=` to set it equal to that particular value. We'll want to make sure we avoid these sort of error by using something like an HTML validator: https://validator.w3.org/nu/#textarea

You can paste your HTML into there and it will give you instant feedback regarding the structure of your document.

**Comment by KellyDesigns** [comment]
Thanks, will start using validator to check my code.
