### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by Default4152** [KellyDesigns/prj-rev-bwfs-tea-cozy#5]
Important for errors - The website isn't meeting the specification as it appears off center. I would recommend going through your CSS using Google Chrome Developer Tools and messing with the values until you can get it to become more center. 

Here is a link to download Google Chrome if you do not have it: https://www.google.com/chrome/

Here is a resource that goes over this process using Google Chrome: https://www.youtube.com/watch?v=Z3HGJsNLQ1E

**Comment by KellyDesigns** [comment]
Thank you for the advice!
