### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [KellyDesigns/prj-rev-bwfs-tea-cozy#6]
Grade: **Needs Improvement**

This project was super easy to test as the HTML and CSS were very organized and formatted nicely. I really liked your usage of semantic elements as they are important for communicating goals of our HTML.

Moving forward, I would recommend doing the following:

* Make the website closer to the specification
* Take advantage of Google Chrome Developer Tools to debug your CSS
* Use an HTML validator to ensure there are no HTML errors

After this, if you feel you need a more solid understanding, I would then recommend going through the project once more as an additional challenge.

Hope this helps!

**Comment by KellyDesigns** [comment]
Thanks for reviewing my project. I struggled with this project but I also had decided to do the project over again.
